#!/bin/bash

#     job name:
#PBS -N Neuveal-Conv
#PBS -P RDS-FEI-NRMMCI-RW
#PBS -q compute 

#     how many cpus?
#PBS -l ncpus=16

#PBS -l pmem=6000mb

# How long to run the job? (hours:minutes:seconds)
#PBS -l walltime=96:0:0

#     Name of output file:
#PBS -o trainlog.txt

#     Environmental varibles to make it work:
#PBS -J 1-8
luajit leave_one_out.lua --singlefold 1 --foldidx ${PBS_ARRAY_INDEX} --datapath ./data/OP --threads 16
